//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppQuanLyCyberGame.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicChat
    {
        public int message_id { get; set; }
        public Nullable<int> sender_id { get; set; }
        public Nullable<int> receiver_id { get; set; }
        public string message_text { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
