//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppQuanLyCyberGame.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillDetail
    {
        public int BillId { get; set; }
        public int ItemId { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> Number { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Item Item { get; set; }
    }
}
