//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppQuanLyCyberGame.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientComputer
    {
        public int Id { get; set; }
        public Nullable<bool> CCStatus { get; set; }
        public Nullable<int> CCType { get; set; }
    
        public virtual ClientComputerType ClientComputerType { get; set; }
    }
}
